// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4E5m3JDYL2UnIMXzMHzIC2Rr1m4WFsEA',
    appId: '1:112678842774:web:d233f155c15ca34550edb7',
    messagingSenderId: '112678842774',
    projectId: 'ecommerce-app-d7f17',
    authDomain: 'ecommerce-app-d7f17.firebaseapp.com',
    storageBucket: 'ecommerce-app-d7f17.firebasestorage.app',
    measurementId: 'G-Y2720TP8VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSsw0ne50HG5opI1Zm8a-XB8hCsd15p8U',
    appId: '1:112678842774:android:f6ee657088c11aa350edb7',
    messagingSenderId: '112678842774',
    projectId: 'ecommerce-app-d7f17',
    storageBucket: 'ecommerce-app-d7f17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBavTrWdV_-J2XALfsDiEZKCKG0gw_hkdY',
    appId: '1:112678842774:ios:e4072a445429807e50edb7',
    messagingSenderId: '112678842774',
    projectId: 'ecommerce-app-d7f17',
    storageBucket: 'ecommerce-app-d7f17.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );
}
